from integral import *
import msvcrt
import pyautogui


val = input(">")
start("anaconda prompt")
instant_write("E:")
instant_write("cd projects_python")
instant_write("mkdir "+val)
instant_write("cd "+val)
instant_write("conda create -n tensorflow pip python=3.8")
keyboard.wait("esc")
time.sleep(1)
instant_write("conda activate tensorflow")
keyboard.wait("esc")
time.sleep(1)
instant_write("pip install --ignore-installed --upgrade tensorflow==2.2.0")
keyboard.wait("esc")
time.sleep(1)
instant_write('python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"')
keyboard.wait("esc")
time.sleep(1)
instant_write("mkdir Tensorflow")
instant_write("cd Tensorflow")
instant_write("git clone https://github.com/tensorflow/models.git")
keyboard.wait("esc")
time.sleep(2)
instant_write("cd models\\research")
instant_write("protoc object_detection/protos/*.proto --python_out=.")
instant_write("pip install pycocotools-windows")
instant_write("pip install cython")
instant_write("pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI")
keyboard.wait("esc")
start("git cmd")
instant_write("cd e:")
instant_write("cd projects_python/"+val+"/tensorflow/models/research")
instant_write("cp object_detection/packages/tf2/setup.py .")
keyboard.wait("esc")
press("alt+f4")
instant_write("python -m pip install .")
instant_write("python object_detection/builders/model_builder_tf2_test.py")

